server:
  port: 8761
spring:
  application:
    name: discovery-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${server.port}/eureka/
    healthcheck:
      enabled: true # for Actuator
    register-with-eureka: false
    fetch-registry: false